### ISSUE TITLE
Do you any algorithm on Swift?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/swift#1]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [swift](https://github.com/AllAlgorithms/swift) this case

**Comment by Soumya44** [comment]
I am in

**Comment by khawajafarooq** [comment]
Not accepting PRs anymore? 🤔

**Comment by abranhe** [comment]
@khawajafarooq 😃 Yes we are accepting all pull requests, we still a small team, that's why it takes time.

**Comment by vldmrkl** [comment]
I'll work on graph algorithms if you don't mind.

**Comment by abranhe** [comment]
@klymenkoo it would be great!

**Comment by islamnurdin** [comment]
Check the new PRs :)

**Comment by vshmatok** [comment]
https://github.com/AllAlgorithms/swift/pull/29

**Comment by vshmatok** [comment]
https://github.com/AllAlgorithms/swift/pull/30

**Comment by rasyadh** [comment]
Hi, I'd like to add several design pattern on Swift
Here's the PR #33
